### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'aws'

### ISSUE THREAD

**Issue by tur-ing** [bfansports/dynamodb-to-elasticsearch#2]
I have built and uploaded the Lambda function package (manually) and on testing the function in the AWS console, I get the following error:

```START RequestId: 162f500e-fa91-11e6-bde3-3ddf4f17ca14 Version: $LATEST
invalid literal for int() with base 10: 'aws': ValueError
Traceback (most recent call last):
  File "/var/task/lambda.py", line 33, in lambda_handler
    connection_class=RequestsHttpConnection
  File "/var/task/elasticsearch/client/__init__.py", line 171, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 41, in _normalize_hosts
    if parsed_url.port:
  File "/usr/lib64/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'aws'
```
Please note:

`lambda.py` is exactly the same file as `src/DynamoToES/index.py`

That's the format of the Elasticsearch cluster URL:

`arn:aws:es:eu-central-1:29490xxxxx:domain/frxxxx`

**Comment by tur-ing** [comment]
I've used the execution role instead of the ES URL, issue solved!
